---
title: Peer Review Questions
subtitle: Jasmine Zhao
jupyter: econ470-a0kernel
---


1. Code Review and Efficiency (10 points): Are there any parts of the code that seem inefficient or redundant? How could these sections be optimized for better performance or clarity?

The data cleaning and uploading code had some parts that were repetitive. Some code chunks were repeated around 4 times, and without commenting, I was not exactly sure why that was the case. I also believe that the same csvs were read in multiple times, which again, the reasoning was unclear to me as no context was provided. As for the analysis code (the questions and answers), most of the code seemed very reasonable to me. There were a few questions where the answer was provided in various formats (a table and a graph), which was not unhelpful information, but did not directly answer the questions the homework asked and did not seem necessary (Q1, Q2).

2. Comparison of Results (10 points): How well do their results compare with your own? Are there any areas where the two analyses are particularly different?

My results were somewhat similar to my peer's. There were areas that followed the same trends, but had different numbers, and some were more different. The values in question 1 were different between our two outputs, however, the general trend was similar (a decrease through 2015, and increasing after that). Question 2's graphs were slightly different, but overall, had the same trend. For question 3, the numbers themselves were quite different, but we had the same general trend of magnitude and direction for the DID estimates. This makes sense considering the difference observed in question 1. Question 5 and 6 had very similar results. Our findings for question 7 were silghtly different (~-17 vs. ~-20). The event study graphs had the same general trends. 

In general, although our exact values did not usually align, the same trends were observed, and the same conclusions could be drawn from both of our results.

3. Replicability and Documentation (10 points): Are you able to clone your peer’s repository and replicate their results?

I was able to clone the repository and replicate the same results. The method I used was downloading a zip file of the entire repository, uploading it into jupyter, and pushing it into a new repository.

4. Diagnosing Replication (10 points): If you were unable to replicate their results using their code, what do you think is the central problem? If you were able to replicate, are there things that could have been changed (e.g., code structure, documentation, commenting, etc) that would have made it easier?

I was able to replicate the code, however there were some things that would have made the process easier and more clear. First, there were no comments at all throughout any of the code I ran (data upload/cleaning, questions). Adding comments would have just made it clearer what each code chunk's function was, and would have helped in directing me to the right place if I was ever confused or ran into errors. Another thing that would have been helpful is having an updated README.md. The structure of the repository made it a bit confusing to figure out where things were, like the actual answer code file itself, which was in the submission 1 folder. Moreover, it would have been helpful since my peer did reference their homework 4 work/code, and I was unsure where specifically in their hw 4 folder they were trying to reference. This led to some trial and error that I believe could have been avoided with some more commenting and descriptions. Finally, my peer used absolute paths for all of the paths. This meant that I had to change all of the paths to match mine, and since our folder structures differed (for both their reference file, hw 5, and hw 4, which they often drew from), I had to try various paths until I got to where they were referencing, which was unclear without commenting throughout the code.

5. Final Thoughts (10 points): How might you update your own code based on your review of your peer’s work?

Our processes certainly had some differences, but I learned a lot from my peer's code. My peer often used "sorted(Path("path").glob("*"))" to find all of the paths within one location, which I have never used or seen before, but I think could definitely be a helpful tool for me in the future to increase efficiency. I also think their code for the regressions (5-7) was more efficient than what I typically use, so I would probably update my code to reflect that process. Also, I felt that their qmd files overall were very clean and well done, and through working with their code, I learned a few things that I know would make my qmd files look better as well. 

